---
version: 1
update_configs:
  - package_manager: 'php:composer'
    directory: './'
    update_schedule: 'live'
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: 'all'
    commit_message:
      prefix: 'feat'
      prefix_development: 'chore'
  - package_manager: 'javascript'
    directory: './'
    update_schedule: 'live'
    automerged_updates:
      - match:
          dependency_type: 'all'
    commit_message:
      prefix: 'chore'
      prefix_development: 'chore'
